export const PLACEMENT_LIST_REQUEST = 'PLACEMENT_LIST_REQUEST'
export const PLACEMENT_LIST_SUCCESS = 'PLACEMENT_LIST_SUCCESS'
export const PLACEMENT_LIST_FAIL = 'PLACEMENT_LIST_FAIL'

export const PLACEMENT_DETAILS_REQUEST = 'PLACEMENT_DETAILS_REQUEST'
export const PLACEMENT_DETAILS_SUCCESS = 'PLACEMENT_DETAILS_SUCCESS'
export const PLACEMENT_DETAILS_FAIL = 'PLACEMENT_DETAILS_FAIL'

export const PLACEMENT_DELETE_REQUEST = 'PLACEMENT_DELETE_REQUEST'
export const PLACEMENT_DELETE_SUCCESS = 'PLACEMENT_DELETE_SUCCESS'
export const PLACEMENT_DELETE_FAIL = 'PLACEMENT_DELETE_FAIL'
export const PLACEMENT_DELETE_RESET = 'PLACEMENT_DELETE_RESET'

export const PLACEMENT_CREATE_REQUEST = 'PLACEMENT_CREATE_REQUEST'
export const PLACEMENT_CREATE_SUCCESS = 'PLACEMENT_CREATE_SUCCESS'
export const PLACEMENT_CREATE_FAIL = 'PLACEMENT_CREATE_FAIL'
export const PLACEMENT_CREATE_RESET = 'PLACEMENT_CREATE_RESET'

export const PLACEMENT_UPDATE_REQUEST = 'PLACEMENT_UPDATE_REQUEST'
export const PLACEMENT_UPDATE_SUCCESS = 'PLACEMENT_UPDATE_SUCCESS'
export const PLACEMENT_UPDATE_FAIL = 'PLACEMENT_UPDATE_FAIL'
export const PLACEMENT_UPDATE_RESET = 'PLACEMENT_UPDATE_RESET'
